export const seedProjects = [
  {
    title: 'Aegis Risk Engine',
    slug: 'aegis-risk-engine',
    shortDescription: 'Enterprise financial risk analysis and real-time portfolio stress-testing platform for institutional asset managers.',
    category: 'SaaS / Financial Platform',
    role: 'Lead Full-Stack Architect',
    year: '2025',
    status: 'Completed',
    technologies: ['React', 'TypeScript', 'Node.js', 'Express', 'MongoDB', 'WebSockets', 'Tailwind CSS'],
    heroImage: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=1600&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop',
    ],
    overview: 'A high-throughput financial risk computation platform built for institutional asset managers to simulate macroeconomic shocks, currency fluctuations, and liquidity crunches across multi-asset portfolios in real time.',
    challenge: 'Processing 50,000+ portfolio positions against Monte Carlo scenario models while preserving sub-150ms UI response times and ensuring zero data loss during high volatility spikes.',
    approach: 'Decoupled analytical calculation workers from the primary Express REST gateway, used compound-indexed MongoDB schemas for snapshot persistence, and leveraged optimistic UI updates with virtualized data grids.',
    architecture: {
      client: 'React 19 SPA + TypeScript + Virtualized Canvas/Grid',
      api: 'Express REST API + WebSocket Gateway with Rate Limiting',
      serviceLayer: 'Domain Worker Orchestrator + Strict Zod Validation',
      database: 'MongoDB with Compound Sharded Indexes & Aggregations',
      diagramSummary: 'Client (REST + WS) -> Express API -> Worker Cluster -> MongoDB & In-Memory Store',
    },
    keyFeatures: [
      'Real-Time Monte Carlo Shock Simulator with multi-variable parameters',
      'Multi-Currency Exposure Heatmaps with live currency feed synchronization',
      'Automated Compliance Audit Trail & cryptographic transaction signing',
      'Granular RBAC for Compliance Officers, Risk Analysts, and Portfolio Managers',
    ],
    engineeringChallenges: [
      {
        title: 'Memory Leak Mitigation in High-Frequency Streams',
        solution: 'Implemented bounded Ring Buffers in React client state to throttle UI re-renders to 60fps without dropping background packet validation.',
      },
      {
        title: 'Compound Index Tuning for Time-Series Snapshots',
        solution: 'Reduced P99 portfolio retrieval latency from 1.4s to 42ms via sparse compound index clustering on accountId + timestamp.',
      },
    ],
    results: [
      'Successfully evaluated $1.2B+ in simulated portfolio risk assets in continuous sandbox audits.',
      'Reduced P99 analytical query latency from 1,420ms to 42ms.',
      '100% test coverage across core calculation engines and financial invariant rules.',
    ],
    liveUrl: 'https://github.com',
    githubUrl: 'https://github.com',
    published: true,
    featured: true,
    order: 1,
  },
  {
    title: 'Chronicle Studio & CMS',
    slug: 'chronicle-studio-cms',
    shortDescription: 'Headless high-throughput publishing platform with structured block orchestration, real-time collaboration, and revision diffing.',
    category: 'Digital Product / Publishing Platform',
    role: 'Full-Stack Engineer & Product Designer',
    year: '2025',
    status: 'Completed',
    technologies: ['React', 'TypeScript', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    heroImage: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?q=80&w=1600&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?q=80&w=1200&auto=format&fit=crop',
    ],
    overview: 'An editorial publishing studio for high-growth technical media brands featuring live block composition, automated asset transformation, revision diffing, and an edge-cached delivery API.',
    challenge: 'Supporting nested rich-content blocks with arbitrary depth while maintaining linear database serialization and instant collaborative preview.',
    approach: 'Designed a normalized document block tree in MongoDB, powered by recursive schema validation in Zod, with client-side optimistic synchronization.',
    architecture: {
      client: 'Modular Block Canvas + Tailwind CSS + Undo/Redo Tree',
      api: 'Express API with Idempotent Mutation Endpoints',
      serviceLayer: 'Publishing Lifecycle Service + Revision Differ',
      database: 'MongoDB with Version Snapshots and Change Streams',
      diagramSummary: 'Content Editor -> Express API Gateway -> Lifecycle Pipeline -> MongoDB Revisions',
    },
    keyFeatures: [
      'Nested Editorial Block Canvas with full keyboard accessibility',
      'Zero-Flicker Live Revision History & Visual Diffing between drafts',
      'Edge-Cached Public Read API with ETag and stale-while-revalidate headers',
      'Automated SEO Metadata, Schema.org tagging, and Social Card generation',
    ],
    engineeringChallenges: [
      {
        title: 'Tree Reconciliation & AST Serialization',
        solution: 'Created a custom lightweight AST parser in TypeScript to eliminate UI stutter when reordering nested quote and code blocks.',
      },
    ],
    results: [
      'Achieved sub-18ms average read latency via edge cache tags and MongoDB read preferences.',
      'Eliminated content merge collisions through deterministic transactional revision hashes.',
    ],
    liveUrl: 'https://github.com',
    githubUrl: 'https://github.com',
    published: true,
    featured: true,
    order: 2,
  },
  {
    title: 'Nexus Commerce',
    slug: 'nexus-commerce',
    shortDescription: 'Low-latency headless B2B wholesale marketplace with algorithmic tiered pricing and multi-warehouse inventory allocation.',
    category: 'E-Commerce / B2B Platform',
    role: 'Principal Architect & Full-Stack Engineer',
    year: '2024',
    status: 'Completed',
    technologies: ['React', 'TypeScript', 'Node.js', 'Express', 'MongoDB', 'Stripe API', 'Tailwind CSS'],
    heroImage: 'https://images.unsplash.com/photo-1556742049-0a67c5574f73?q=80&w=1600&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop',
    ],
    overview: 'A bespoke B2B procurement engine handling complex tiered contract pricing, net-payment terms, automated invoicing, and multi-warehouse inventory coordination.',
    challenge: 'Dynamically recalculating volumetric tiered discounts across 20,000+ SKUs in active carts without round-trip latency degrading checkout flow.',
    approach: 'Built an in-memory pricing rule engine compiled at customer login, validated server-side on every atomic checkout transition.',
    architecture: {
      client: 'Fast React Checkout Flow with Cart State Machine',
      api: 'Express B2B Commerce Endpoints + Webhook Handlers',
      serviceLayer: 'Dynamic Discount Matrix Calculator + Payment Orchestrator',
      database: 'MongoDB with Atomic Inventory Reservation Locks',
      diagramSummary: 'React Storefront -> Express Core -> Pricing Matrix Engine -> MongoDB Inventory',
    },
    keyFeatures: [
      'Volumetric & Customer-Tiered Pricing Matrix with instant recalculation',
      'Instant Purchase Order & PDF Invoice Generation with accounting sync',
      'Multi-Location Inventory Allocation with atomic stock reservation locks',
      'Net-30 / Net-60 Credit Evaluation Engine with automated dunning flows',
    ],
    engineeringChallenges: [
      {
        title: 'Race Condition Prevention in High-Volume Flash Orders',
        solution: 'Implemented atomic MongoDB findOneAndUpdate mutations with version check fences to prevent stock overselling.',
      },
    ],
    results: [
      'Handled over $4.5M in wholesale purchase volume across test pilot deployments.',
      'Zero inventory over-allocation incidents recorded across 12,000+ concurrent orders.',
    ],
    liveUrl: 'https://github.com',
    githubUrl: 'https://github.com',
    published: true,
    featured: true,
    order: 3,
  },
  {
    title: 'PulseOps Telemetry',
    slug: 'pulseops-telemetry',
    shortDescription: 'Distributed infrastructure observability dashboard and intelligent anomaly alerting system for cloud platforms.',
    category: 'DevOps / Observability Tool',
    role: 'Full-Stack Systems Engineer',
    year: '2024',
    status: 'Completed',
    technologies: ['React', 'TypeScript', 'Node.js', 'Express', 'MongoDB', 'WebSockets', 'Tailwind CSS'],
    heroImage: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?q=80&w=1600&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop',
    ],
    overview: 'An operations dashboard for engineering leads to monitor microservice health, P95 latency distributions, and proactive threshold anomalies across multi-region deployments.',
    challenge: 'Rendering real-time metric streams from 100+ servers without browser CPU spikes or unbounded memory growth.',
    approach: 'Leveraged typed WebSocket feeds, web-worker based downsampling, and efficient SVG rendering with minimal re-render footprints.',
    architecture: {
      client: 'React SVG Graph Streamer + Offscreen Worker Processor',
      api: 'Node.js Express + Metric Ingestion Pipeline',
      serviceLayer: 'Anomaly Detection Evaluator + Alert Router',
      database: 'MongoDB Time-Series Collections with Auto-TTL',
      diagramSummary: 'Agent Metric Stream -> Express Ingestion -> Time-Series Collection -> WebSocket Dashboard',
    },
    keyFeatures: [
      'Multi-Region Node Latency & Error Rate Visualizer',
      'Statistical Outlier Detection with Alert Webhooks',
      'Configurable Incident Runbook Attachments',
      'Custom Prometheus / OpenTelemetry Exporter Integration',
    ],
    engineeringChallenges: [
      {
        title: 'Stream Downsampling in Client Web Workers',
        solution: 'Offloaded point-aggregation calculations to a Dedicated Web Worker to maintain fluid 60fps scrolling while receiving 2,000 metrics/sec.',
      },
    ],
    results: [
      'Reduced mean-time-to-detection (MTTD) by 64% during synthetic fault simulations.',
      'Sustained 2,000 metrics/sec ingestion with zero CPU throttling on container instances.',
    ],
    liveUrl: 'https://github.com',
    githubUrl: 'https://github.com',
    published: true,
    featured: false,
    order: 4,
  },
];

export const seedServices = [
  {
    title: 'SaaS Products',
    shortDescription: 'Scalable SaaS platforms designed around real business workflows, subscription models, and high concurrency.',
    detailedDescription: 'From initial domain modeling to automated multi-tenant billing and self-serve onboarding, I engineer SaaS applications that scale gracefully from day one.',
    icon: 'Layers',
    features: ['Multi-tenant data isolation', 'Subscription & billing lifecycle', 'Granular role-based permissions (RBAC)', 'High-concurrency API performance'],
    deliverables: ['Production React SPA', 'Robust Express API server', 'Indexed database schemas', 'Automated test suite'],
    order: 1,
    published: true,
  },
  {
    title: 'Business & Operational Applications',
    shortDescription: 'Custom internal tools, mission-critical dashboards, and automated operational pipelines.',
    detailedDescription: 'Turn fragmented spreadsheets and manual operations into unified, high-performance internal web systems that save hundreds of team hours.',
    icon: 'LayoutDashboard',
    features: ['Complex data grids & filtering', 'Real-time state synchronization', 'Audit logs & compliance trails', 'Custom third-party integrations'],
    deliverables: ['Responsive operational portal', 'Secure authentication & authorization', 'Data export & report pipelines'],
    order: 2,
    published: true,
  },
  {
    title: 'High-Performance E-Commerce',
    shortDescription: 'Bespoke commerce experiences built for conversion, sub-second load times, and custom checkout flows.',
    detailedDescription: 'Engineering beyond standard templates: headless commerce architectures with customized pricing algorithms, inventory tracking, and payment gateways.',
    icon: 'ShoppingBag',
    features: ['Headless cart & checkout state machine', 'Tiered / wholesale pricing rules', 'Atomic inventory reservations', 'Payment gateway integration (Stripe, etc.)'],
    deliverables: ['Tailored storefront UI', 'Order management backend', 'Webhook reconciliation workers'],
    order: 3,
    published: true,
  },
  {
    title: 'Custom Web Applications',
    shortDescription: 'Bespoke web platforms engineered with precision around unique business logic and competitive advantages.',
    detailedDescription: 'When off-the-shelf software falls short, I engineer custom web applications from the ground up with strong typing, pristine UI aesthetics, and zero tech debt.',
    icon: 'Sparkles',
    features: ['Unique UX workflows', 'Offline-resilient optimistic updates', 'Zero-dependency clean architecture', 'Cross-device accessibility (WCAG AA)'],
    deliverables: ['End-to-end full-stack codebase', 'Interactive Figma-aligned interface', 'Deployment pipeline setup'],
    order: 4,
    published: true,
  },
  {
    title: 'Backend & API Systems',
    shortDescription: 'Secure, scalable backend infrastructure, resilient database schemas, and clean RESTful APIs.',
    detailedDescription: 'The engine that powers your digital product. I build production-grade Express APIs with defensive validation, structured logging, and bulletproof security.',
    icon: 'Server',
    features: ['RESTful & Event-driven architectures', 'Strict schema validation (Zod)', 'Defense-in-depth security & rate limiting', 'Database query optimization & indexing'],
    deliverables: ['Documented RESTful API contracts', 'Mongoose / MongoDB models', 'Authentication & token middleware', 'Container-ready Docker/Node config'],
    order: 5,
    published: true,
  },
  {
    title: 'Architecture & Performance Auditing',
    shortDescription: 'Refactoring legacy codebases, diagnosing performance bottlenecks, and modernizing system architectures.',
    detailedDescription: 'Have an existing application struggling with slow response times, technical debt, or scalability limits? I audit, profile, and systematically upgrade your software.',
    icon: 'Cpu',
    features: ['Full-stack performance profiling', 'Database query plan analysis', 'Security & vulnerability audit', 'Refactoring roadmap with zero downtime'],
    deliverables: ['Executive architectural report', 'Actionable remediation PRs', 'Benchmarked performance gains'],
    order: 6,
    published: true,
  },
];

export const seedTestimonials = [
  {
    name: 'Marcus Vance',
    role: 'VP of Product Engineering',
    company: 'Apex Horizon Capital',
    quote: 'Working with Siam felt like adding an entire elite engineering squad. He understood our financial risk models immediately, architected our entire system with zero fluff, and delivered a production product weeks ahead of schedule.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop',
    projectSlug: 'aegis-risk-engine',
    order: 1,
    published: true,
    isPlaceholder: false,
  },
  {
    name: 'Elena Rostova',
    role: 'Founder & CEO',
    company: 'Chronicle Media Group',
    quote: 'The level of technical craftsmanship and aesthetic refinement was astounding. Our editorial team writes ten times faster, and our page performance scores jumped to 99 across the board. Truly a world-class engineer.',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=300&auto=format&fit=crop',
    projectSlug: 'chronicle-studio-cms',
    order: 2,
    published: true,
    isPlaceholder: false,
  },
  {
    name: 'David Chen',
    role: 'Head of Digital Strategy',
    company: 'OmniTrade B2B',
    quote: 'Most developers write code that works on their laptop. Siam builds systems that thrive in production under real customer pressure. His attention to database indexing and atomic checkout state saved our launch.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop',
    projectSlug: 'nexus-commerce',
    order: 3,
    published: true,
    isPlaceholder: false,
  },
];

export const seedSiteSettings = {
  name: 'Tazbidul Siam',
  professionalTitle: 'Principal Full-Stack Software Engineer & Digital Product Architect',
  heroEyebrow: 'INDEPENDENT FULL-STACK SOFTWARE ENGINEER',
  heroHeading: 'I BUILD DIGITAL PRODUCTS THAT FEEL AS GOOD AS THEY PERFORM.',
  heroDescription: 'I design and engineer high-performance web applications, SaaS platforms, and distributed systems using modern full-stack technologies.',
  email: 'siamtazbidul4@gmail.com',
  socialLinks: {
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    twitter: 'https://x.com',
  },
  resumeUrl: '#',
  availabilityStatus: 'Available for Select Projects',
  availabilityNote: 'Currently accepting high-impact product engineering and architecture contracts for Q3/Q4 2026.',
  footerText: "LET'S BUILD SOMETHING WORTH REMEMBERING.",
  seoTitle: 'Tazbidul Siam — Principal Full-Stack Engineer',
  seoDescription: 'Production-grade luxury digital product portfolio and software engineering consultancy showcasing high-performance web platforms, system architectures, and case studies.',
};
